# Generated by Django 3.0.4 on 2020-04-02 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e2943590-5d39-4a3a-9692-c87a6c976ea6'), editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
                'db_table': 'album',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e2943590-5d39-4a3a-9692-c87a6c976ea6'), editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_nasc', models.DateField(verbose_name='Data Nascimento')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='EducadorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e2943590-5d39-4a3a-9692-c87a6c976ea6'), editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_nasc', models.DateField(verbose_name='Data Nascimento')),
            ],
            options={
                'verbose_name': 'Educador',
                'verbose_name_plural': 'Educadores',
                'db_table': 'educador',
            },
        ),
        migrations.CreateModel(
            name='TurmaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e2943590-5d39-4a3a-9692-c87a6c976ea6'), editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('ano_turma', models.CharField(max_length=4)),
                ('periodo', models.CharField(max_length=30)),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='portal_fotos.AlunoModel')),
                ('educadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='portal_fotos.EducadorModel')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turma',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='FotoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e2943590-5d39-4a3a-9692-c87a6c976ea6'), editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, default='/fotos/sem-foto.png', null=True, upload_to='fotos')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_fotos.AlbumModel')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'db_table': 'foto',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='albummodel',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='portal_fotos.TurmaModel'),
        ),
    ]
